# Generated by Django 5.1.4 on 2026-02-14 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g., Toyota, Honda, Maruti Suzuki', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('model_name', models.CharField(help_text='e.g., Innova, City, Swift', max_length=100)),
                ('variant', models.CharField(blank=True, default='', help_text='e.g., VXi, ZXi, Sigma, Delta', max_length=100)),
                ('year_from', models.IntegerField(help_text='First year of manufacture')),
                ('year_to', models.IntegerField(blank=True, help_text='Last year of manufacture (blank if still in production)', null=True)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi_automatic', 'Semi-Automatic'), ('cvt', 'CVT')], max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='vehicle.vehiclemake')),
            ],
            options={
                'ordering': ['make__name', 'model_name', 'variant'],
                'indexes': [models.Index(fields=['make', 'model_name', 'variant'], name='vehicle_veh_make_id_00b47f_idx')],
                'constraints': [models.UniqueConstraint(fields=('make', 'model_name', 'variant', 'year_from', 'fuel_type', 'transmission'), name='unique_vehicle_model_combination')],
            },
        ),
    ]
