# Generated by Django 5.1.4 on 2026-02-16 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['make__name', 'model_name']},
        ),
        migrations.RemoveConstraint(
            model_name='vehiclemodel',
            name='unique_vehicle_model_combination',
        ),
        migrations.RemoveIndex(
            model_name='vehiclemodel',
            name='vehicle_veh_make_id_00b47f_idx',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='year_to',
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['make', 'model_name'], name='vehicle_veh_make_id_900e36_idx'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('make', 'model_name', 'fuel_type', 'transmission'), name='unique_vehicle_model_combination'),
        ),
    ]
