# Generated by Django 5.1.4 on 2026-02-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase/Stock In'), ('sale', 'Sale/Stock Out'), ('return', 'Customer Return'), ('adjustment', 'Stock Adjustment'), ('damage', 'Damaged/Written Off')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('reference_number', models.CharField(blank=True, help_text='PO number, Invoice number, etc.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_logs', to='inventory.inventory')),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
