# Generated by Django 5.1.4 on 2026-02-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorylog'),
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='job_card_item',
            field=models.ForeignKey(blank=True, help_text='Link to job card if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobcard.jobcarditem'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['transaction_type'], name='inventory_i_transac_4801aa_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorylog',
            index=models.Index(fields=['transaction_date'], name='inventory_i_transac_c6dfc5_idx'),
        ),
    ]
