# Generated by Django 5.1.4 on 2026-03-03 11:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorylog_job_card_item_and_more'),
        ('invoice', '0002_remove_invoiceitem_deleted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='job_card_item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='low_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='invoice_item',
            field=models.ForeignKey(blank=True, help_text='Link to job card if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoiceitem'),
        ),
        migrations.AddField(
            model_name='inventorylog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='inventory.category'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_parts', to='inventory.uom'),
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
