# Generated by Django 5.1.4 on 2026-09-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_custom_role_ac7cf6_idx',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
