# Generated by Django 5.1.4 on 2026-09-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_customuser_user_custom_role_ac7cf6_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'permissions': [('view_dashboard', 'Can view dashboard')], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
