# Generated by Django 5.1.4 on 2026-02-15 10:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('inventory', '0002_inventorylog'),
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job_card_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('vehicle_number', models.CharField(help_text='Vehicle registration/plate number', max_length=20)),
                ('odometer_reading', models.IntegerField(blank=True, help_text='Current odometer reading in km', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='customer.customer')),
                ('vehicle_model', models.ForeignKey(blank=True, help_text='Link to vehicle master data (make/model/variant)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='job_cards', to='vehicle.vehiclemodel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_card_usages', to='inventory.inventory')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_card_items', to='jobcard.jobcard')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['vehicle_model'], name='jobcard_job_vehicle_2c3a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['customer'], name='jobcard_job_custome_1440fa_idx'),
        ),
        migrations.AddIndex(
            model_name='jobcard',
            index=models.Index(fields=['vehicle_number'], name='jobcard_job_vehicle_2e8c8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcarditem',
            constraint=models.UniqueConstraint(fields=('job_card', 'inventory'), name='unique_jobcard_inventory'),
        ),
    ]
