# Generated by Django 5.1.4 on 2026-02-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobcarditem',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='jobcarditem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='jobcarditem',
            name='is_deleted',
        ),
    ]
