# Generated by Django 5.1.4 on 2026-02-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='is_deleted',
        ),
    ]
